services:
  - type: web
    name: backend-quevedo-tour
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true

  - type: pspg
    name: postgres-quevedo-tour
    plan: free
    databaseName: db-quevedo-tour
    databaseUser: postgres
